require("user.plugins")
require("user.sets")
require("user.colors")
require("user.illuminate")
require("user.autocommands")
require("user.treesitter")
require("user.keymaps")
require("user.comment")
require("user.lsp")
require("user.cmp")
require("user.telescope")
require("user.trouble")
--[[ require("user.neogit") ]]
require("user.toggleterm")
